[packages.plasma]
pacman = [
  "plasma-desktop",
  "dolphin",
  "konsole",
  "breeze-gtk",
  "kde-gtk-config",
  "plasma-nm",
  "plasma-pa",
  "spectacle",
]

[packages.core]
pacman = [
  "ly",
  "xdg-desktop-portal",
  "tuned-ppd",
  "pipewire",
  "pipewire-pulse",
  "wireplumber",
  "brightnessctl",
  "noto-fonts",
  "ttf-nerd-fonts-symbols",
]

[packages.niri]
pacman = [
  "niri",
  "quickshell",
  "wl-mirror",
  "alsa-utils",
]

[packages.apps]
pacman = [
  "git",
  "kitty",
  "neovim",
  "fastfetch",
  "zsh",
  "github-cli",
]
